Backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from  . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    path("learn/", include("coding.urls")),
    path("tournament/", include("tournaments.urls")),
    path("", include("user.urls")),
    path("accounts/", include("allauth.urls")),
    path("battle/", include("battle.urls")),
    path("win/", views.win, name="win"),
    path("lose/", views.lose, name="lose"),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password/password_reset_form.html"),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="password/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_success.html"),
         name='password_reset_complete'),
]

battle/urls.py
from django.urls import path

from . import views

app_name = "battle"

urlpatterns = [
    path("", views.index, name="battle"),
    path('get-updated-value/', views.get_updated_value, name='get_updated_value'),
    path("<str:room_name>/", views.room, name="room"),


]

coding/urls.py
from django.urls import path
from . import views

app_name = "coding"

urlpatterns = [
    path("", views.LearningPageView.as_view(), name="learn"),
    path("QuestionSelection/python/", views.pagepython, name="question_python"),
    path("QuestionSelection/cpp/", views.pagecpp, name="question_cpp"),
    path("QuestionSelection/java/", views.pagejava, name="question_java"),
    path("QuestionSelection/c/", views.pagec, name="question_c"),
    path("code", views.coding, name="coding")
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard, name="dashboard")

]

tournaments/urls.py
from django.urls import path
from . import views
app_name = "tournament"
urlpatterns = [
    path("", views.getpage, name="participate")#pattren
]

user/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path('signup/', views.UserSignupPage.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),

]

Backend/views.py
import random
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from battle.models import UserMatching, ButtonClick
from coding.judgement import submission, get_status, languages
from django.db.models import Q
from django.contrib.auth import get_user_model
import uuid
from coding.models import CodingQuestions, ProblemStatus, TestCases
from django.contrib.auth.decorators import login_required
import time
from django.views.decorators.csrf import csrf_exempt
from dashboard.processing_dashboard import ProcessUserData


def win(request):
    user = get_user_model()
    button_clicker = ButtonClick.objects.filter(user=user).first()
    if button_clicker:
        button_clicker.delete()

    # Delete UserMatching object
    user_matching = UserMatching.objects.filter(Q(user1=user) | Q(user2=user)).first()
    if user_matching:
        user_matching.delete()
    return render(request, 'backend/win.html')


def lose(request):
    user = get_user_model()
    button_clicker = ButtonClick.objects.filter(user=user).first()
    if button_clicker:
        button_clicker.delete()

    # Delete UserMatching object
    user_matching = UserMatching.objects.filter(Q(user1=user) | Q(user2=user)).first()
    if user_matching:
        user_matching.delete()
    return render(request, 'backend/lose.html')

templates/backend/1home_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" sizes="389x320" href="{% static 'image/favicon.png' %}">
    <title>Home | CLASH OF BUGS</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap">
    <link rel="stylesheet" href="{% static 'css/1home_update.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/locomotive-scroll@3.5.4/dist/locomotive-scroll.css">



</head>
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.4/gsap.min.js"
        integrity="sha512-EZI2cBcGPnmR89wTgVnN3602Yyi7muWo8y1B3a8WmIv1J9tYG+udH4LvmYjLiGp37yHB7FfaPBo8ly178m9g4Q=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.4/gsap.min.js"
        integrity="sha512-EZI2cBcGPnmR89wTgVnN3602Yyi7muWo8y1B3a8WmIv1J9tYG+udH4LvmYjLiGp37yHB7FfaPBo8ly178m9g4Q=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.4/ScrollTrigger.min.js"
        integrity="sha512-OzC82YiH3UmMMs6Ydd9f2i7mS+UFL5f977iIoJ6oy07AJT+ePds9QOEtqXztSH29Nzua59fYS36knmMcv79GOg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/locomotive-scroll@3.5.4/dist/locomotive-scroll.js"></script>
<div id="loader">
    <h3>Hello </h3>
    <h3>Coder's<br></h3>

</div>
<div id="main">
    <div class="container">

        <div class="d-element">
            <script type="module" src="https://unpkg.com/@splinetool/viewer@1.0.38/build/spline-viewer.js"></script>
            <spline-viewer url="https://prod.spline.design/xBz2ceEWNGW3RaG7/scene.splinecode"></spline-viewer>

        </div>
        <div class="logo_hid"></div>
        <div id="cob1">

            <h1 id="heading-home">
                <span>C</span><span>L</span><span>A</span><span>S</span><span>H</span>
                <span class="space"></span>
                <span>O</span><span>F</span>
                <span class="space"></span>
                <span>B</span><span>U</span><span>G</span><span>'S</span>
            </h1>

        </div>
        <nav>
            <div class="logo">
                <img width="100%" height="120%" id=logo src="{% static 'image/sitelogo.png' %}" alt="">
            </div>
            <div class="rectangle">
                {% if not request.user.is_authenticated %}
                <div class="rect">
                    <a href="{% url 'users:signup' %}">
                        <button>
                            Register
                        </button>
                    </a>
                </div>

                <div class="rect1">
                    <a href="{% url 'users:login' %}">
                        <button>
                            Sign In
                        </button>
                    </a>
                </div>
                {% else %}
                <div class="rect">
                    <a href="{% url 'coding:learn' %}">
                        <button>
                            Learn
                        </button>
                    </a>
                </div>

                <div class="rect1">
                    <a href="{% url 'battle:battle' %}">
                        <button>
                            Battle
                        </button>
                    </a>
                </div>
                 <div class="rect1">
                    <a href="{% url 'tournament:participate' %}">
                        <button>
                            Tournament
                        </button>
                    </a>
                </div>
                <div class="rect1">
                    <a href="{% url 'dashboard:dashboard' %}">
                        <button>
                            Dashboard
                        </button>
                    </a>
                </div>
                {% endif %}

            </div>
        </nav>
        <div id="page1-content">


            <div id="infotxt">
                <div class="bug">
                    <div class="card">
                        <img src="{% static 'image/bug_img.jpg' %}" alt="img">
                    </div>
                </div>
                <div class="text1">
                    <h1>Clash of Bugs</h1><br>
                    <h3>Clash of Bugs is an innovative coding platform designed for coding enthusiasts, students, and competitive programmers. </h3>
                </div>

            </div>
        </div>

    </div>


    <div class="page2">
        <div class="frame">
            <div class="overlap-group">
                <div class="dot  dot-0"></div>
                <div class="dot  dot-1"></div>
                <div class="dot  dot-2"></div>
                <div class="dot  dot-3"></div>
                <div class="dot  dot-4"></div>
                <div class="dot  dot-5"></div>
                <div class="dot  dot-6"></div>
                <div class="dot  dot-7"></div>
                <div class="dot  dot-8"></div>
                <div class="dot  dot-9"></div>
                <div class="dot  dot-10"></div>
                <div class="dot  dot-11"></div>
                <div class="dot  dot-12"></div>
                <div class="dot  dot-13"></div>
                <div class="dot  dot-14"></div>
                <div class="dot  dot-15"></div>
                <div class="dot  dot-16"></div>
                <div class="dot  dot-17"></div>
                <div class="dot  dot-18"></div>
                <div class="dot  dot-19"></div>
                <div class="dot  dot-20"></div>
                <div class="dot  dot-21"></div>
                <div class="dot  dot-22"></div>
                <div class="dot  dot-23"></div>
                <div class="dot  dot-24"></div>
                <div class="dot  dot-25"></div>
                <div class="dot  dot-26"></div>
                <div class="dot  dot-27"></div>
                <div class="dot  dot-28"></div>
                <div class="dot  dot-29"></div>
                <div class="dot  dot-30"></div>
                <div class="dot  dot-31"></div>
                <div class="dot  dot-32"></div>
                <div class="dot  dot-33"></div>
                <div class="dot  dot-34"></div>
                <div class="dot  dot-35"></div>
                <div class="dot  dot-36"></div>
                <div class="dot  dot-37"></div>
                <div class="dot  dot-38"></div>
                <div class="dot  dot-39"></div>
                <div class="dot  dot-40"></div>
                <div class="dot  dot-41"></div>
                <div class="dot  dot-42"></div>
                <div class="dot  dot-43"></div>
                <div class="dot  dot-44"></div>
                <div class="dot  dot-45"></div>
                <div class="dot  dot-46"></div>
                <div class="dot  dot-47"></div>
                <div class="dot  dot-48"></div>
                <div class="dot  dot-49"></div>
                <div class="dot  dot-50"></div>
                <div class="dot  dot-51"></div>
                <div class="dot  dot-52"></div>
                <div class="dot  dot-53"></div>
                <div class="dot  dot-54"></div>
                <div class="dot  dot-55"></div>
                <div class="dot  dot-56"></div>
                <div class="dot  dot-57"></div>
                <div class="dot  dot-58"></div>
                <div class="dot  dot-59"></div>
                <div class="dot  dot-60"></div>
                <div class="dot  dot-61"></div>
                <div class="dot  dot-62"></div>
                <div class="dot  dot-63"></div>
                <div class="dot  dot-64"></div>
                <div class="dot  dot-65"></div>
                <div class="dot  dot-66"></div>
                <div class="dot  dot-67"></div>
                <div class="dot  dot-68"></div>
                <div class="dot  dot-69"></div>
                <div class="dot  dot-70"></div>
                <div class="dot  dot-71"></div>
                <div class="dot  dot-72"></div>
                <div class="dot  dot-73"></div>
                <div class="dot  dot-74"></div>
                <div class="dot  dot-75"></div>
                <div class="dot  dot-76"></div>
                <div class="dot  dot-77"></div>
                <div class="dot  dot-78"></div>
                <div class="text-wrapper-2">CLASH OF BUG’S</div>
            </div>
        </div>
    </div>
    <div class="page3">
        <div class="pg3txt">
            <h3>Coding & Challenges</h3><br>
            <h1>Programming is the art of algorithm design and the craft of debugging errant code.</h1>
        </div>
    </div>
    <div class="page4" id="future">
        <video id="ad" src="" autoplay muted loop></video>
        <a href="{% url 'users:signup' %}">
        <div class="ftext">
            <h1>think of future</h1>
            <button>join us</button>
        </div>
        </a>
    </div>

    <footer class="footer" style="height:40vh;">
        <div class="left-section">
            <img id=logo-foot src="{% static 'image/sitelogo.png' %}" alt="">

            <div>
                <ul>
                    <li><a href="{% url 'users:home' %}">Home</a></li>
                    <li><a href="{% url 'tournament:participate' %}">Tournaments</a></li>
                    <li><a href="{% url 'battle:battle' %}">Battles</a></li>
                    <li><a href="{% url 'coding:learn' %}">Learn</a></li>
                </ul>
                <div class="copyright"><p> © by Trivix labs pvt ltd</p></div>
            </div>
        </div>
        <div class="right-section">
            <p>Contact Information:</p>
            <p>Email: clashofbugs.com@gmail.com</p>
            <p>Phone: +91 70877 58864 </p>

        </div>
    </footer>

    <script src="{% static 'js/1home_update.js' %}"></script>
</body>
</html>



templates/backend/base.html
<!doctype html>

<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Title{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'backend/base.css' %}">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>



    {% block styles %} {% endblock %}
</head>
<body>
{% block content %}

<nav class="navbar">
    <div class="logo">
        <a href="{% url 'users:home' %}">
            <img src="{% static 'image/sitelogo.png' %}" alt="logo"
                        width="130px">
        </a> <!-- Your Logo -->
    </div>
    <ul class="nav">
        <li class="nav-items"><a href=""><span class="link-text">Tournament</span><i class="fa-solid fa-store"></i></a></li>
        <li class="nav-items"><a href=""><span class="link-text">Learn</span><i class="fa-solid fa-book"></i></a>
        </li>
        <li class="nav-items"><a href=""><span class="link-text">Battle</span><i
                class="fa-solid fa-weapon"></i></a></li>
    </ul>
    <div class="box" style="display:flex; flex-direction:rows;">

<!--    <a href="{% url 'users:login' %}" class="btn" style="margin-right:10px">Login <i class="fa-solid fa-chevron-right ok"></i></a>-->
<!--     <a href="{% url 'users:signup' %}" class="btn">Sign up <i class="fa-solid fa-chevron-right ok"></i></a>-->
<!---->
    </div>
</nav>

hello

{% endblock %}
</body>
</html>

templates/backend/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	    {% load static %}
    {% load crispy_forms_tags %}
    {% load socialaccount %}
	<meta charset="UTF-8">
	<title>Login | Form</title>
	    <link rel="icon" type="image/png" sizes="389x320" href="{% static 'image/favicon.png' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{% static 'backend/signup.css' %}">
	<link rel="stylesheet" href="{% static 'backend/navbar.css' %}">

    <style>
		.signin-form {
  margin: 0 auto; /* Center the button horizontally */
  max-width: 320px;
  display: flex;
  flex-direction: row;
  justify-content: center; /* Center the button horizontally */
  align-items: center;
  padding: 0.5rem 1.4rem;
  font-size: 0.875rem;
  line-height: 1.25rem;
  font-weight: 700;
  text-align: center;
  font-family: "Montserrat", sans-serif;
  border-radius: 0.5rem;
  border: 1px solid rgba(255, 255, 255, 0.25);
  gap: 0.75rem;
  color: #c4d2dc;
  background-color: #19242b;
  cursor: pointer;
  transition: all 0.25s cubic-bezier(0, 0.87, 0.12, 1);
}

.signin-form:hover {
  transform: scale(1.025);
}

.signin-form:active {
  transform: scale(0.975);
}

button svg {
  height: 24px;
  width: auto;
}


	</style>
</head>
<body>


	<div class="container signinForm">
<form method="POST">
	{% csrf_token %}
		<div class="form signin ">
			<h2>Sign In</h2>
			<div class="inputBox">
				{{ form.username }}
<!--				<input type="text" required="required">-->
				<i class="fa-regular fa-user"></i>
				<span>username</span>
			</div>
			<div class="inputBox">
				{{ form.password }}
<!--				<input type="password" required="required">-->
				<i class="fa-solid fa-lock"></i>
				<span>password</span>
			</div>
			<div class="forgot password">
				<p><a href="{% url 'password_reset' %}" class="create">forgot password?</a></p>
			</div>
			<div class="inputBox">
				<input type="submit" value="Login">
			</div>
			<p>Not Registered ? <a href="{% url 'users:signup' %}" class="create">Create an account</a></p>
		</div>
    </form>


    <br />
    <a href="{% provider_login_url 'google' %}">
            <button class="signin-form">
        <svg
          viewBox="0 0 256 262"
          preserveAspectRatio="xMidYMid"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M255.878 133.451c0-10.734-.871-18.567-2.756-26.69H130.55v48.448h71.947c-1.45 12.04-9.283 30.172-26.69 42.356l-.244 1.622 38.755 30.023 2.685.268c24.659-22.774 38.875-56.282 38.875-96.027"
            fill="#4285F4"
          ></path>
          <path
            d="M130.55 261.1c35.248 0 64.839-11.605 86.453-31.622l-41.196-31.913c-11.024 7.688-25.82 13.055-45.257 13.055-34.523 0-63.824-22.773-74.269-54.25l-1.531.13-40.298 31.187-.527 1.465C35.393 231.798 79.49 261.1 130.55 261.1"
            fill="#34A853"
          ></path>
          <path
            d="M56.281 156.37c-2.756-8.123-4.351-16.827-4.351-25.82 0-8.994 1.595-17.697 4.206-25.82l-.073-1.73L15.26 71.312l-1.335.635C5.077 89.644 0 109.517 0 130.55s5.077 40.905 13.925 58.602l42.356-32.782"
            fill="#FBBC05"
          ></path>
          <path
            d="M130.55 50.479c24.514 0 41.05 10.589 50.479 19.438l36.844-35.974C195.245 12.91 165.798 0 130.55 0 79.49 0 35.393 29.301 13.925 71.947l42.211 32.783c10.59-31.477 39.891-54.251 74.414-54.251"
            fill="#EB4335"
          ></path>
        </svg>
        Sign in with Google
      </button>
    </a>
	</div>
</body>
</html>

templates/backend/lose.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" sizes="389x320" href="{% static 'image/favicon.png' %}">
    <title>Win Page</title>
    <style>

        body {
            display: flex;
             background: linear-gradient(to bottom, #141e30, #243b55);
            flex-direction: column;

            height: 100vh;
            width:100%;
            margin: 0;
        }

        #win-text {
            color: red; /* Set the text color to green */
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        #win-button {
            padding: 10px 20px;
            font-size: 18px;
            cursor: pointer;
        }
    </style>
    <link rel="stylesheet" href="{% static 'dashboard/button.css' %}">
    <link rel="stylesheet" href="{% static 'backend/navbar.css' %}">
</head>
<body>
<nav class="navbar">
    <div class="logo"><a href="{% url 'users:home' %}" class="home-link"><img width="100px" id = logo src="{% static 'image/sitelogo.png' %}" alt=""></a>
    </div>
    <ul class="nav-list">
      <li><a href="{% url 'tournament:participate' %}"><button >Tournaments</button></a></li>
      <li><a href="{% url 'coding:learn' %}"><button >Learn</button></a></li>
      <li><a href="{% url 'battle:battle' %}"><button >Battles</button></a></li>
    </ul>

    <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello" class="nav-image">
              </a>
    <div class="menu-toggle">
    <input id="checkbox" type="checkbox" class="menu-btn">
    <label class="toggle" for="checkbox">

      <div id="bar1" class="bars"></div>
      <div id="bar2" class="bars"></div>
      <div id="bar3" class="bars"></div>

    </label>
    <div class="overlay-menu">
      <div class="profile-image">
          <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello">
              </a>
      </div>
      <div class="buttons-menu">
        <a href="{% url 'tournament:participate' %}">
        <button>
          Tournaments
        </button>
        </a>
        <a href="{% url 'coding:learn' %}">
        <button>
          Learn
       </button>
        </a>
        <a href="{% url 'battle:battle' %}">
        <button>
          Battles
        </button>
        </a>
      </div>
  </div>

    </div>
  </nav>
<div style="margin-left:45%; margin-top:20%;">
    <div id="win-text" style="margin-left:25px;">Lost</div>
    <a href="{% url 'battle:battle' %}" >
    <button id="win-button" class="das">Battle again</button>
        </a>
    </div>
</body>
</html>

templates/backend/nav.html
{% extends "backend/base.html" %}
{% load static %}
{% block title %}
{% endblock %}
{% block styles %}
{% endblock %}
{% block content %}
<nav class="navbar">
    <div class="logo"><img width="100px" id = logo src= "{% static '/logo.png' %}" alt="">
    </div>
    <ul class="nav-list">
<!--      <li><a href="./tournaments.html"><button>Tournaments</button></a></li>-->
<!--      <li><a href=""><button href="#">Learn</button></a></li>-->
      <li><a href="/battle"><button>Battles</button></a></li>
    </ul>
    {% if not request.user.is_authenticated %}
    <div class="login-btns-nav">
      <a href="{% url 'users:login' %}" class="login-btn-glow">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Login
      </a>
      <a href="#" class="login-btn-glow">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Sign up
      </a>
    </div>
    {% else %}
    <div></div>
    {% endif %}
    <div class="menu-toggle">
    <input id="checkbox" type="checkbox" class="menu-btn">
    <label class="toggle" for="checkbox">

      <div id="bar1" class="bars"></div>
      <div id="bar2" class="bars"></div>
      <div id="bar3" class="bars"></div>

    </label>
    <div class="overlay-menu">
        {% if not request.user.is_authenticated %}
        <div class="login-btns-menu">
          <a href="#" class="login-btn-glow">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Login
          </a>
          <a href="#" class="login-btn-glow">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Sign up
          </a>
        </div>
    {% endif %}
      <div class="buttons-menu">
<!--        <a href="">-->
<!--        <button>-->
<!--          Tournaments-->
<!--        </button>-->
<!--        </a>-->
<!--        <a href="">-->
<!--        <button>-->
<!--          Learn-->
<!--        </button>-->
<!--        </a>-->
        <a href="/battle">
        <button>
          Battles
        </button>
        </a>
      </div>
  </div>

    </div>
  </nav>

  <script src="{% static '/navbar.js' %}"></script>
{% endblock %}

templates/backend/win.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
        <link rel="icon" type="image/png" sizes="389x320" href="{% static 'image/favicon.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Win Page</title>
    <style>

        body {
            display: flex;
             background: linear-gradient(to bottom, #141e30, #243b55);
            flex-direction: column;

            height: 100vh;
            width:100%;
            margin: 0;
        }

        #win-text {
            color: green; /* Set the text color to green */
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        #win-button {
            padding: 10px 20px;
            font-size: 18px;
            cursor: pointer;
        }
    </style>
    <link rel="stylesheet" href="{% static 'dashboard/button.css' %}">
    <link rel="stylesheet" href="{% static 'backend/navbar.css' %}">
</head>
<body>
<nav class="navbar">
    <div class="logo"><a href="{% url 'users:home' %}" class="home-link"><img width="100px" id = logo src="{% static 'image/sitelogo.png' %}" alt=""></a>
    </div>
    <ul class="nav-list">
      <li><a href="{% url 'tournament:participate' %}"><button >Tournaments</button></a></li>
      <li><a href="{% url 'coding:learn' %}"><button >Learn</button></a></li>
      <li><a href="{% url 'battle:battle' %}"><button >Battles</button></a></li>
    </ul>

    <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello" class="nav-image">
              </a>
    <div class="menu-toggle">
    <input id="checkbox" type="checkbox" class="menu-btn">
    <label class="toggle" for="checkbox">

      <div id="bar1" class="bars"></div>
      <div id="bar2" class="bars"></div>
      <div id="bar3" class="bars"></div>

    </label>
    <div class="overlay-menu">
      <div class="profile-image">
          <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello">
              </a>
      </div>
      <div class="buttons-menu">
        <a href="{% url 'tournament:participate' %}">
        <button>
          Tournaments
        </button>
        </a>
        <a href="{% url 'coding:learn' %}">
        <button>
          Learn
       </button>
        </a>
        <a href="{% url 'battle:battle' %}">
        <button>
          Battles
        </button>
        </a>
      </div>
  </div>

    </div>
  </nav>
<div style="margin-left:45%; margin-top:20%;">
    <div id="win-text" style="margin-left:25px;">Won</div>
    <a href="{% url 'battle:battle' %}" >
    <button id="win-button" class="das">Battle again</button>
        </a>
    </div>
</body>
</html>