Backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from  . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    path("learn/", include("coding.urls")),
    path("tournament/", include("tournaments.urls")),
    path("", include("user.urls")),
    path("accounts/", include("allauth.urls")),
    path("battle/", include("battle.urls")),
    path("win/", views.win, name="win"),
    path("lose/", views.lose, name="lose"),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password/password_reset_form.html"),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="password/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_success.html"),
         name='password_reset_complete'),
]

battle/urls.py
from django.urls import path

from . import views

app_name = "battle"

urlpatterns = [
    path("", views.index, name="battle"),
    path('get-updated-value/', views.get_updated_value, name='get_updated_value'),
    path("<str:room_name>/", views.room, name="room"),


]

coding/urls.py
from django.urls import path
from . import views

app_name = "coding"

urlpatterns = [
    path("", views.LearningPageView.as_view(), name="learn"),
    path("QuestionSelection/python/", views.pagepython, name="question_python"),
    path("QuestionSelection/cpp/", views.pagecpp, name="question_cpp"),
    path("QuestionSelection/java/", views.pagejava, name="question_java"),
    path("QuestionSelection/c/", views.pagec, name="question_c"),
    path("code", views.coding, name="coding")
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard, name="dashboard")

]

tournaments/urls.py
from django.urls import path
from . import views
app_name = "tournament"
urlpatterns = [
    path("", views.getpage, name="participate")#pattren
]

user/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path('signup/', views.UserSignupPage.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),

]

coding/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class CodingQuestions(models.Model):
    PROBLEM_HARDNESS_CHOICES = (
        (0, 'easy'),
        (1, 'medium'),
        (2, 'hard')
    )
    title = models.TextField()
    primary_text = models.TextField(unique=True)
    input_text = models.CharField(max_length=2000)
    output_text = models.CharField(max_length=2000)
    input_example = models.CharField(max_length=1024)
    output_example = models.CharField(max_length=1024)
    topic = models.CharField(max_length=100)
    xp = models.IntegerField()
    problem_hardness = models.IntegerField(
        choices=PROBLEM_HARDNESS_CHOICES,
        default=0
    )

    def __str__(self):
        return f"{self.primary_text}"


class ProblemStatus(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(CodingQuestions, on_delete=models.CASCADE)
    solution = models.TextField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.question.primary_text}"


class TestCases(models.Model):
    key = models.ForeignKey(CodingQuestions, on_delete=models.CASCADE)
    test_case_input = models.TextField()
    test_case_output = models.TextField()

    def __str__(self):
        return f"{self.key.primary_text}"

coding/views.py
import time

from django.middleware.csrf import get_token
from django.shortcuts import render, HttpResponse, redirect
from .processing_coding import ProcessCodingData
from .models import CodingQuestions, TestCases, ProblemStatus
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse
from .judgement import submission, get_status, languages


# Create your views here.
@method_decorator(login_required(login_url="/login"), name='get')
class LearningPageView(View):
    template_name = "coding/selection.html"

    # @login_required(login_url="/login")

    def get(self, request, *args, **kwargs):
        process_class = ProcessCodingData()
        _, python_solved_questions = process_class.get_solved_question(User=request.user, Topic="python")
        _, cpp_solved_questions = process_class.get_solved_question(User=request.user, Topic="cpp")
        _, java_solved_questions = process_class.get_solved_question(User=request.user, Topic="java")
        _, c_solved_questions = process_class.get_solved_question(User=request.user, Topic="c")
        context = {
            "csrf_token": get_token(request),
            "python": python_solved_questions,
            "cpp": cpp_solved_questions,
            "java": java_solved_questions,
            "c": c_solved_questions
        }
        return render(request, self.template_name, context)


# @method_decorator(login_required(login_url="/login"), name='get')
# class QuestionPageView(View):
#     template_name = "coding/question_selection.html"
#
#     # @login_required(login_url="/login")
#     def get(self, request, *args, **kwargs):
#         data_object = CodingQuestions
#         PROBLEM_HARDNESS_CHOICES = ['easy', 'medium', 'hard']
#         data_object = data_object.objects.filter(topic="python")
#
#         level_values = [PROBLEM_HARDNESS_CHOICES[i.problem_hardness] for i in data_object]
#
#         context = {
#             'python': zip(data_object, level_values),  # Pair each question with its level
#         }
#         if request.method == 'POST':
#             data = request.POST.get('id')
#             return HttpResponse(data)
#         else:
#             # return HttpResponse('no')
#             return render(request, self.template_name, context)
@login_required(login_url='/login')
def pagepython(request, *args, **kwargs):
    data_object = CodingQuestions
    PROBLEM_HARDNESS_CHOICES = ['easy', 'medium', 'hard']
    data_object = data_object.objects.filter(topic="python")

    level_values = [PROBLEM_HARDNESS_CHOICES[i.problem_hardness] for i in data_object]

    context = {
        'python': zip(data_object, level_values),  # Pair each question with its level
    }
    if request.method == 'POST':
        data = request.POST.get('questionbtn')
        request.session['data'] = data
        return redirect('/learn/code')
    else:
        # return HttpResponse('no')
        return render(request, "coding/question_selection.html", context)


@login_required(login_url='/login')
def pagecpp(request, *args, **kwargs):
    data_object = CodingQuestions
    PROBLEM_HARDNESS_CHOICES = ['easy', 'medium', 'hard']
    data_object = data_object.objects.filter(topic="cpp")

    level_values = [PROBLEM_HARDNESS_CHOICES[i.problem_hardness] for i in data_object]

    context = {
        'python': zip(data_object, level_values),  # Pair each question with its level
    }
    if request.method == 'POST':
        data = request.POST.get('questionbtn')
        request.session['data'] = data
        return redirect('/learn/code')
    else:
        # return HttpResponse('no')
        return render(request, "coding/question_selection.html", context)


@login_required(login_url='/login')
def pagejava(request, *args, **kwargs):
    data_object = CodingQuestions
    PROBLEM_HARDNESS_CHOICES = ['easy', 'medium', 'hard']
    data_object = data_object.objects.filter(topic="java")

    level_values = [PROBLEM_HARDNESS_CHOICES[i.problem_hardness] for i in data_object]

    context = {
        'python': zip(data_object, level_values),  # Pair each question with its level
    }
    if request.method == 'POST':
        data = request.POST.get('questionbtn')
        request.session['data'] = data
        return redirect('/learn/code')
    else:
        # return HttpResponse('no')
        return render(request, "coding/question_selection.html", context)


@login_required(login_url='/login')
def pagec(request, *args, **kwargs):
    data_object = CodingQuestions
    PROBLEM_HARDNESS_CHOICES = ['easy', 'medium', 'hard']
    data_object = data_object.objects.filter(topic="c")

    level_values = [PROBLEM_HARDNESS_CHOICES[i.problem_hardness] for i in data_object]

    context = {
        'python': zip(data_object, level_values),  # Pair each question with its level
    }
    if request.method == 'POST':
        data = request.POST.get('questionbtn')
        request.session['data'] = data
        return redirect('/learn/code')
    else:
        # return HttpResponse('no')
        return render(request, "coding/question_selection.html", context)


@login_required(login_url='/login')
def coding(request):
    data = request.session.get('data', None)
    question = CodingQuestions.objects.get(id=data)
    input_question = question.input_example.split('/n')
    output = question.output_example.split('/n')
    compiler_message = "-"
    stdin = "-"
    stdout = "-"
    if request.method == "POST":
        request.user.xp = request.user.xp + question.xp
        request.user.save()
        try:
            qs = ProblemStatus.objects.get(user=request.user, question=question)
            qs.solution = request.POST.get('code')
            qs.save()
        except:
            qs = ProblemStatus.objects.create(user=request.user, question=question, solution=request.POST.get('code'))
            qs.save()
        test_cases = TestCases.objects.filter(key=CodingQuestions.objects.get(id=data))
        results = []
        test = []
        x = 1
        for i in test_cases:
            a = submission(str(request.POST.get('code')), str(request.POST.get('lang')), languages,
                           stdin=str(i.test_case_input),
                           stdout=str(i.test_case_output))

            time.sleep(1)
            a = get_status(a.get('token'))
            test.append(x)
            x += 1

            results.append([a.get('stdout'), i.test_case_input, a.get('time')])
        qs = ProblemStatus.objects.get(user=request.user, question=question)
        return render(request, 'coding/learning_page.html',
                      {'question': question, 'input_q': input_question, 'output_q': output,
                       "result": results, 'test': test, "pre": qs})

    else:
        return render(request, 'coding/learning_page.html',
                      {'question': question, 'input_q': input_question, 'output_q': output,
                       "compiler_message": compiler_message, "stdin": stdin, "stdout": stdout})

coding/templates/coding/learning_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>coding</title>
    <link rel="stylesheet" href="{% static 'battle/battle.css' %}">
<link rel="icon" type="image/png" sizes="389x320" href="{% static 'image/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'backend/navbar.css' %}">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        .section{display: none}
        .active-section{display:block}

          body{
    background: linear-gradient(to bottom, #141e30, #243b55);
    height: 100vh;
  }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.20.0/min/vs/editor/editor.main.min.css" integrity="sha512-XjO5XYWl8u7tYF3CItEHgoWh8rtQmDeSzPJq4+4PIrbak7TiqeKbWv/4ZwHZ1HAf5dIWHXoguA/jobn2psKZ7w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
<body>
<nav class="navbar">
    <div class="logo"><a href="{% url 'users:home' %}" class="home-link"><img width="100px" id = logo src="{% static 'image/sitelogo.png' %}" alt=""></a>
    </div>
    <ul class="nav-list">
      <li><a href="{% url 'tournament:participate' %}"><button >Tournaments</button></a></li>
      <li><a href="{% url 'coding:learn' %}"><button >Learn</button></a></li>
      <li><a href="{% url 'battle:battle' %}"><button >Battles</button></a></li>
    </ul>

    <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello" class="nav-image">
              </a>
    <div class="menu-toggle">
    <input id="checkbox" type="checkbox" class="menu-btn">
    <label class="toggle" for="checkbox">

      <div id="bar1" class="bars"></div>
      <div id="bar2" class="bars"></div>
      <div id="bar3" class="bars"></div>

    </label>
    <div class="overlay-menu">
      <div class="profile-image">
          <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello">
              </a>
      </div>
      <div class="buttons-menu">
        <a href="{% url 'tournament:participate' %}">
        <button>
          Tournaments
        </button>
        </a>
        <a href="{% url 'coding:learn' %}">
        <button>
          Learn
       </button>
        </a>
        <a href="{% url 'battle:battle' %}">
        <button>
          Battles
        </button>
        </a>
      </div>
  </div>

    </div>
  </nav>

  <script>var require = { paths: { 'vs' : 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.20.0/min/vs' }};
  </script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.20.0/min/vs/loader.min.js" integrity="sha512-gWqaPfGsZiCkYB6e5mNN4SMRpEvLGItLBqgOAoyLSKtDxWS2O1YPcOeGTy8d8l00gqc8rVue9ae/ncZqhmfj4g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.20.0/min/vs/editor/editor.main.nls.min.js" integrity="sha512-4XY3/LL6Plkq2tXMnatY+se07ZhwFMkZehD5Z68HrKoSL3BTyLDjwFomhUWixKu8VUw6jWe/8RXT1WtH95lLFg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.20.0/min/vs/editor/editor.main.min.js" integrity="sha512-CK3czr9gLG2z/ygdSM+gNenkN9AShfpW4gMjVyY06VgFHLoc4OCoO92Z8UkcBwVX0ufoYbJw3IVs1mHfXQeI3g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
 <script>
      var codeContent = $.trim($('#CodeBlock').text());
      $('#CodeBlock').html('');

        var editorCodeBlock = monaco.editor.create(document.getElementById('CodeBlock'),{
              value: codeContent,
              language : "csharp",
              theme: "vs-dark",
              lineNumbers: "on" ,
              glyphMargin: false,
              vertical: 'auto',
              horizontal: 'auto ' ,
              verticalScrollbarSize: 10,
              horizontalScrollbarSize: 10,
              scrollBeyondLastLine: false,
              readOnly: false,
              automaticLayout:  true,
              minimap: {
                  enabled: true
              },
              lineHeight:20,
          });
          $ ("#CodeBlock").height((editorCodeBlock.getModel() .getLineCount()*40.2)+30);

          function showContainer(containerId) {
    var containers = document.getElementsByClassName('container');

    // Hide all containers
    for (var i = 0; i < containers.length; i++) {
        containers[i].style.display = 'none';
    }

    // Show the selected container
    var selectedContainer = document.getElementById(containerId);
    if (selectedContainer) {
        selectedContainer.style.display = 'block';
    }
}

function showContainer1(containerId) {
    var containers1 = document.getElementsByClassName('test-case');

    // Hide all containers
    for (var i = 0; i < containers1.length; i++) {
        containers1[i].style.display = 'none';
    }

    // Show the selected container
    var selectedContainer1 = document.getElementById(containerId);
    if (selectedContainer1) {
        selectedContainer1.style.display = 'block';
    }
}

  </script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js"></script> -->
    <div class="desktop">

        <div class="question">
            <div class="heading"> {{question.title}} </div>
            <h2>Problem</h2>
            <div class="ques"> {{ question.primary_text }} </div>
            <h2>Input</h2>
            <div class="ques"> {{question.input_text}}
                <pre class="err">
                    <span></span>
                   {% for i in input_q %}
                    <span>{{ i }}</span>
                    {% endfor %}
                </pre>
            </div>
            <h2>Output</h2>
            <div class="ques"> {{ question.output_text }}
                <pre class="err">
                    <span></span>
                    {% for i in output_q %}
                    <span>{{ i }}</span>
                    {% endfor %}
                </pre>
            </div>
        </div>
        <form method="POST">
            {% csrf_token %}
        <div class="coding">
            <div class="language">
                Select Language

            <select id="codingLanguages" name="lang">
                <option value="C++">C++</option>
                <option value="C">C</option>
                <option value="python" selected>Python</option>
                <option value="java">Java</option>

            </select>
        </div>

            <div id="editor">

                <pre id='CodeBlock'>

                    {{pre.solution}}


              </pre>
              </div>




        </div>
        <div class="test">
            <div class="radio-inputs">
                <label class="radio">
                    <!-- <input type="radio" name="radio" checked="checked" onclick="showContainer('container1')"> -->
                  <span class="name">Test Cases</span>
                </label>
                <!-- <label class="radio">
                    <input type="radio" name="radio" onclick="showContainer('container2')">
                  <span class="name">Custom Inputs</span>
                </label> -->

              </div>
              <div id="container1" class="container">
                <!-- Content for Container 1 -->

<div class="input" id="testcases">
    {% for i in result %}
        <button class="value" onclick="showSection('test{{ forloop.counter }}')" type="button">
            TEST CASE {{ forloop.counter }}
        </button>
    {% endfor %}
</div>

{% for x, y, z  in result %}
    <div id="test{{ forloop.counter }}" style="background: #0e1726; overflow:auto;" class="test-case">
        <div class="text_test_cases">
            Time taken:
        </div>
        <div class="err" id="output_box">
            <span id="compilermessage">
                {{ z }}s
            </span>
        </div>
        <div class="text_test_cases">
            STDIN:
        </div>
        <div class="err" id="output_box2">
            <span id="stdin">
                {{ y }}
            </span>
        </div>
        <div class="text_test_cases">
            STDOUT:
        </div>
        <div class="err" id="output_box3">
            <span id="stdout">
                {{x}}
            </span>
        </div>
    </div>
{% endfor %}

<script>
    function showSection(sectionId) {
        const sections = document.querySelectorAll('.test-case');
        sections.forEach(section => {
            section.style.display = 'none';
        })

        const sectionToShow = document.getElementById(sectionId);

        if (sectionToShow) {
            sectionToShow.style.display = 'block';
        } else {
            console.log('Section not found!');
        }
    }
</script>



            </div>
            <input type="hidden" value="hi" name="code" id="hiddenInput">
             <button id="submit" type="submit" > Submit
              </button>
              </div>
            </form>


            <!-- <div id="container2" class="container" >
                 Content for Container 2

                <div class="custom-input-container">
                    <textarea name="" id="custom-input" cols="30" rows="6" placeholder="Custom input"></textarea>
            </div>
            </div> -->


        <!-- <div class="clash"></div> -->
  <script>
    var editorCodeBlock; // Declare the editorCodeBlock variable in a wider scope

    // Ensure the document is fully loaded before initializing the editor
    document.addEventListener("DOMContentLoaded", function () {
        var codeContent = $.trim($('#CodeBlock').text());
        $('#CodeBlock').html('');

        editorCodeBlock = monaco.editor.create(document.getElementById('CodeBlock'), {
            value: codeContent,
            language: "python",
            theme: "vs-dark",
            lineNumbers: "on",
            glyphMargin: false,
            vertical: 'auto',
            horizontal: 'auto ',
            verticalScrollbarSize: 10,
            horizontalScrollbarSize: 10,
            scrollBeyondLastLine: false,
            readOnly: false,
            automaticLayout: true,
            minimap: {
                enabled: true
            },
            lineHeight: 20,
        });

        $("#CodeBlock").height((1 * 450.2) + 30);

         editorCodeBlock.onDidChangeModelContent(function () {
            updateHiddenInput();
        });
        document.getElementById('codingLanguages').addEventListener('change', function () {
            updateEditorLanguage();
        });
    });

    function showContainer(containerId) {
        var containers = document.getElementsByClassName('container');

        // Hide all containers
        for (var i = 0; i < containers.length; i++) {
            containers[i].style.display = 'none';
        }

        // Show the selected container
        var selectedContainer = document.getElementById(containerId);
        if (selectedContainer) {
            selectedContainer.style.display = 'block';
        }
    }

    function showContainer1(containerId) {
        var containers1 = document.getElementsByClassName('test-case');

        // Hide all containers
        for (var i = 0; i < containers1.length; i++) {
            containers1[i].style.display = 'none';
        }

        // Show the selected container
        var selectedContainer1 = document.getElementById(containerId);
        if (selectedContainer1) {
            selectedContainer1.style.display = 'block';
        }
    }

    // Function to update editor language based on the selected option
    function updateEditorLanguage() {
        var selectedLanguage = document.getElementById('codingLanguages').value;

        // Map the selected language to the corresponding Monaco language identifier
        var languageMap = {
            'cpp': 'cpp',
            'c': 'c',
            'python': 'python',
            'java': 'java'
        };

        // Get the Monaco language identifier based on the selected option
        var monacoLanguage = languageMap[selectedLanguage] || 'csharp';

        // Set the language of the editor
        monaco.editor.setModelLanguage(editorCodeBlock.getModel(), monacoLanguage);
    }

        function updateHiddenInput() {
        var codeContent = editorCodeBlock.getValue();
        document.getElementById('hiddenInput').value = codeContent;
    }
</script>


</body>
</html>

coding/templates/coding/selection.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" type="image/png" sizes="389x320" href="{% static 'image/favicon.png' %}">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'backend/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'backend/footer.css' %}">
    <link rel="stylesheet" href="{% static 'backend/selection.css' %}">
        <style>
        .progress_python{
    width: {{python}}%;

}
        .progress_java{
    width: {{java}}%;

}.progress_cpp{
    width: {{cpp}}%;

}
        .progress_c{
    width: {{c}}%;

}

    </style>
</head>
<body>
<nav class="navbar" style="margin-top:20px">
    <div class="logo"><a href="{% url 'users:home' %}" class="home-link"><img width="100px" id = logo src="{% static 'image/sitelogo.png' %}" alt=""></a>
    </div>
    <ul class="nav-list">
      <li><a href="{% url 'tournament:participate' %}"><button >Tournaments</button></a></li>
      <li><a href="{% url 'coding:learn' %}"><button >Learn</button></a></li>
      <li><a href="{% url 'battle:battle' %}"><button >Battles</button></a></li>
    </ul>

    <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello" class="nav-image">
              </a>
    <div class="menu-toggle">
    <input id="checkbox" type="checkbox" class="menu-btn">
    <label class="toggle" for="checkbox">

      <div id="bar1" class="bars"></div>
      <div id="bar2" class="bars"></div>
      <div id="bar3" class="bars"></div>

    </label>
    <div class="overlay-menu">
      <div class="profile-image">
          <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello">
              </a>
      </div>
      <div class="buttons-menu">
        <a href="{% url 'tournament:participate' %}">
        <button>
          Tournaments
        </button>
        </a>
        <a href="{% url 'coding:learn' %}">
        <button>
          Learn
       </button>
        </a>
        <a href="{% url 'battle:battle' %}">
        <button>
          Battles
        </button>
        </a>
      </div>
  </div>

    </div>
  </nav>

      <div class="the-selection">
    <div class="section" >
        <div class="container">
            <div class="text-dash">
                In-Progress
            </div>
            <div class="line-dash"></div>
        </div>
        <div class="in-progress">
            <div class="progress-card">
                <div class="name-of-topic">
                    Python
                </div>
                <div class="progress-loader">
                    <div class="progress progress_python"></div>
                </div>
                <div class="percentage">
                    {{python}}% left
                </div>
                <a href="{% url 'coding:question_python' %}" class="progress-button">
                    <button class="progress-btn" id="python-button" onclick="sendToken()">
                        Continue
                    </button>
                </a>
            </div>


            <div class="progress-card">
                <div class="name-of-topic">
                    C++
                </div>
                <div class="progress-loader">
                    <div class="progress progress_cpp"></div>
                </div>
                <div class="percentage">
                    {{cpp}} % left
                </div>
                <a href="{% url 'coding:question_cpp' %}" class="progress-button">
                    <button class="progress-btn">
                        Continue
                    </button>
                </a>
            </div>
            <div class="progress-card">
                <div class="name-of-topic">
                    Java
                </div>
                <div class="progress-loader">
                    <div class="progress progress_java"></div>
                </div>
                <div class="percentage">
                    {{java}} % left
                </div>
                <a href="{% url 'coding:question_java' %}" class="progress-button">
                    <button class="progress-btn">
                        Continue
                    </button>
                </a>
            </div>
            <div class="progress-card">
                <div class="name-of-topic">
                    C
                </div>
                <div class="progress-loader">
                    <div class="progress_c progress"></div>
                </div>
                <div class="percentage">
                    {{c}} % left
                </div>
                <a href="{% url 'coding:question_c' %}" class="progress-button">
                    <button class="progress-btn">
                        Continue
                    </button>
                </a>
            </div>

                             <!-- next-row -->
        </div>


        </div>
      </div>


<footer class="footer" style="height:40vh;">
        <div class="left-section">
            <img id=logo-foot src="{% static 'image/sitelogo.png' %}" alt="">

            <div>
                <ul>
                    <li><a href="{% url 'users:home' %}">Home</a></li>
                    <li><a href="{% url 'tournament:participate' %}">Tournaments</a></li>
                    <li><a href="{% url 'battle:battle' %}">Battles</a></li>
                    <li><a href="{% url 'coding:learn' %}">Learn</a></li>
                </ul>
                <div class="copyright"><p> © by Trivix labs pvt ltd</p></div>
            </div>
        </div>
        <div class="right-section">
            <p>Contact Information:</p>
            <p>Email: clashofbugs.com@gmail.com</p>
            <p>Phone: +91 70877 58864 </p>

        </div>
    </footer>>
</body>


</html>