Backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from  . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    path("learn/", include("coding.urls")),
    path("tournament/", include("tournaments.urls")),
    path("", include("user.urls")),
    path("accounts/", include("allauth.urls")),
    path("battle/", include("battle.urls")),
    path("win/", views.win, name="win"),
    path("lose/", views.lose, name="lose"),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password/password_reset_form.html"),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="password/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_success.html"),
         name='password_reset_complete'),
]

battle/urls.py
from django.urls import path

from . import views

app_name = "battle"

urlpatterns = [
    path("", views.index, name="battle"),
    path('get-updated-value/', views.get_updated_value, name='get_updated_value'),
    path("<str:room_name>/", views.room, name="room"),


]

coding/urls.py
from django.urls import path
from . import views

app_name = "coding"

urlpatterns = [
    path("", views.LearningPageView.as_view(), name="learn"),
    path("QuestionSelection/python/", views.pagepython, name="question_python"),
    path("QuestionSelection/cpp/", views.pagecpp, name="question_cpp"),
    path("QuestionSelection/java/", views.pagejava, name="question_java"),
    path("QuestionSelection/c/", views.pagec, name="question_c"),
    path("code", views.coding, name="coding")
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard, name="dashboard")

]

tournaments/urls.py
from django.urls import path
from . import views
app_name = "tournament"
urlpatterns = [
    path("", views.getpage, name="participate")#pattren
]

user/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path('signup/', views.UserSignupPage.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),

]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


# Create your models here.
class User(AbstractUser):
    xp = models.IntegerField(default=0)
    trophies = models.IntegerField(default=0)
    UID = models.CharField(max_length=100, unique=True)
    Avatar = models.CharField(max_length=24)

    def save(self, *args, **kwargs):
        if not self.UID:
            self.UID = uuid.uuid4().hex
        super().save(*args, **kwargs)

    def clean(self):
        self.email = self.__class__.objects.normalize_email(self.email)
        super().clean()

dashboard/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views import View
from coding.processing_coding import ProcessCodingData


@login_required(login_url="/login")
def dashboard(request, *args, **kwargs):
    process_class = ProcessCodingData()
    _, python_solved_questions = process_class.get_solved_question(User=request.user, Topic="python")
    _, cpp_solved_questions = process_class.get_solved_question(User=request.user, Topic="cpp")
    _, java_solved_questions = process_class.get_solved_question(User=request.user, Topic="java")
    _, c_solved_questions = process_class.get_solved_question(User=request.user, Topic="c")
    context = {
        "python": python_solved_questions,
        "cpp": cpp_solved_questions,
        "java": java_solved_questions,
        "c": c_solved_questions,
        "user":request.user.username
    }

    return render(request, "dashboard.html", context)

dashboard/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User | Dashboard</title>
    <link rel="stylesheet" href="{% static 'dashboard/button.css' %}">
    <link rel="icon" type="image/png" sizes="389x320" href="{% static 'image/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'dashboard/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'backend/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'backend/footer.css' %}">
    <style>
        .progress_python{
    width: {{python}}%;

}
        .progress_java{
    width: {{java}}%;

}.progress_cpp{
    width: {{cpp}}%;

}
        .progress_c{
    width: {{c}}%;

}

    </style>
</head>
<body>
<nav class="navbar">
    <div class="logo"><a href="{% url 'users:home' %}" class="home-link"><img width="100px" id = logo src="{% static 'image/sitelogo.png' %}" alt=""></a>
    </div>
    <ul class="nav-list">
      <li><a href="{% url 'tournament:participate' %}"><button >Tournaments</button></a></li>
      <li><a href="{% url 'coding:learn' %}"><button >Learn</button></a></li>
      <li><a href="{% url 'battle:battle' %}"><button >Battles</button></a></li>
    </ul>

    <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello" class="nav-image">
              </a>
    <div class="menu-toggle">
    <input id="checkbox" type="checkbox" class="menu-btn">
    <label class="toggle" for="checkbox">

      <div id="bar1" class="bars"></div>
      <div id="bar2" class="bars"></div>
      <div id="bar3" class="bars"></div>

    </label>
    <div class="overlay-menu">
      <div class="profile-image">
          <a href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'image/user.png' %}" alt="hello">
              </a>
      </div>
      <div class="buttons-menu">
        <a href="{% url 'tournament:participate' %}">
        <button>
          Tournaments
        </button>
        </a>
        <a href="{% url 'coding:learn' %}">
        <button>
          Learn
       </button>
        </a>
        <a href="{% url 'battle:battle' %}">
        <button>
          Battles
        </button>
        </a>
      </div>
  </div>

    </div>
  </nav>
    <div class="">
        <center>
        <div class="buttons_dashboard">
            <div class="">
                <button type="button" class="dashboard-btns das" id="PI-btn" onclick="showSection('personal_info')">Personal info</button>
                <button type="button" class="dashboard-btns das" id="Cert-btn" onclick="showSection('Certificate')">Certificates</button>
                <!-- <button type="button" class="dashboard-btns" id="Rank-btn" onclick="showSection('Ranking')">Ranking</button> -->
                <a href="{% url 'users:logout' %}"><button type="button" class="das" >Logout ?</button></a>
            </div>
        </div>
    </center>
    <center>
    <div class="section" id="personal_info">
        <div class="hstack">
        <div class="avatar_side">
            <span>
            <div class="avatar">
            <img src="{% static 'image/user.png' %}" alt="" width="100%" height="100%">
            </div>
        </span>

            <div class="vstack">
         <span id="user">@{{user}}</span>

                </div>
        </div>
        <div class="progress_side">
            <h1>Progress</h1>

            <div class="courses">
                <div class="hstack" style="margin: 10px; margin-bottom: 20px;">
                <div class="course-text">
                    Python
                </div>
                <div class="progress-loader">
                    <div class="progress progress_python"></div>
                </div>
                </div>

                <div class="hstack" style="margin: 10px; margin-bottom: 20px;">
                <div class="course-text">
                    C++
                </div>
                <div class="progress-loader">
                    <div class="progress progress_cpp"></div>
                </div>
                </div>
                <div class="hstack" style="margin: 10px; margin-bottom: 20px;">
                <div class="course-text">
                    Java
                </div>
                <div class="progress-loader">
                    <div class="progress progress_java"></div>
                </div>
                </div>
                <div class="hstack" style="margin: 10px; margin-bottom: 20px;">
                <div class="course-text">
                    C
                </div>
                <div class="progress-loader">
                    <div class="progress progress_c"></div>
                </div>
                </div>

            </div>

        </div>
    </div>
    </div>
    </center>


    <center>

        <div class="section" id="Certificate">


            <p style="color:#fff; font-size:40px;">Coming Soon .....</p>
        </div>
        </center>





    </div>
<footer class="footer" style="height:40vh;">
        <div class="left-section">
            <img id=logo-foot src="{% static 'image/sitelogo.png' %}" alt="">

            <div>
                <ul>
                    <li><a href="{% url 'users:home' %}">Home</a></li>
                    <li><a href="{% url 'tournament:participate' %}">Tournaments</a></li>
                    <li><a href="{% url 'battle:battle' %}">Battles</a></li>
                    <li><a href="{% url 'coding:learn' %}">Learn</a></li>
                </ul>
                <div class="copyright"><p> © by Trivix labs pvt ltd</p></div>
            </div>
        </div>
        <div class="right-section">
            <p>Contact Information:</p>
            <p>Email: clashofbugs.com@gmail.com</p>
            <p>Phone: +91 70877 58864 </p>

        </div>
    </footer>>

    <script>
        function showSection(sectionId){
            const sections = document.querySelectorAll('.section');
            sections.forEach(section => {
                section.classList.remove('active-section');
            })


            const sectionToshow = document.getElementById(sectionId);
            sectionToshow.classList.add('active-section')




        }
        showSection('personal_info');
    </script>
</body>
</html>